<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropDownKategori</name>
   <tag></tag>
   <elementGuidId>0979b13e-71f6-47ae-ab20-2b5e06bcc0b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product_category_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='product_category_id']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'product_category_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_category_id</value>
      <webElementGuid>5a1a3675-c5e7-4c09-bff1-7e0d69d596c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='product_category_id']</value>
      <webElementGuid>bf2e6d2e-0b08-4f38-9112-dd49eb040095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori'])[1]/following::select[1]</value>
      <webElementGuid>bbf2d52c-512f-4f66-b86c-c6dd8e20c673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Price can', &quot;'&quot;, 't be blank')])[1]/following::select[1]</value>
      <webElementGuid>98bf85d7-e6d6-4d42-9f25-c2fcf0ae68c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category must exist'])[1]/preceding::select[1]</value>
      <webElementGuid>866fb617-4a52-4105-a9b6-567c02a5e7a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deskripsi'])[1]/preceding::select[1]</value>
      <webElementGuid>d1fc5f14-7197-4c6f-a711-a75596fc08cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>deeac844-17a2-4596-ab09-a898df1b40d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'product[category_id]' and @id = 'product_category_id' and (text() = 'Pilih Kategori
Hobi
Kendaraan
Baju
Elektronik
Kesehatan' or . = 'Pilih Kategori
Hobi
Kendaraan
Baju
Elektronik
Kesehatan')]</value>
      <webElementGuid>330b6044-4939-4b5a-aa5d-f41e444b0744</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
