<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>imgProduct</name>
   <tag></tag>
   <elementGuidId>8ea0a12d-1a1f-4e55-8454-dcba04082f93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-images</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'product_images']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-images</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='input-images']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_images</value>
      <webElementGuid>b10dfaa0-caba-4480-b4ba-11af491dd299</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='input-images']</value>
      <webElementGuid>98b3149d-4976-47df-ba16-1fdce65425a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deskripsi'])[1]/following::div[1]</value>
      <webElementGuid>7fe3706d-a8ad-4ad0-b617-9dc7080146de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori'])[1]/following::div[2]</value>
      <webElementGuid>dd52f0b9-e9af-4e1a-b153-7cdf9dfbd52c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preview'])[1]/preceding::div[2]</value>
      <webElementGuid>87b6f3b3-e91e-4d38-a971-b411beac9f8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terbitkan'])[1]/preceding::div[2]</value>
      <webElementGuid>76329e8e-fa54-4bfe-8fad-c6f3e8caa27e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]</value>
      <webElementGuid>c3e6c5ac-4208-4540-a703-00092096ebc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'input-images']</value>
      <webElementGuid>6b892d70-f8d8-4a8a-a31a-a02ab109b937</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
