<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtMasukPageTitle</name>
   <tag></tag>
   <elementGuidId>9c0e3e3b-5abd-4164-8273-f03504805604</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.fw-bold.mb-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-bold mb-5</value>
      <webElementGuid>70d5c2c4-47fa-4424-a950-aa24df1061db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>c7aac1e9-b278-4b65-a3df-4a51302c8b78</webElementGuid>
   </webElementProperties>
</WebElementEntity>
