<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtHargaProduk</name>
   <tag></tag>
   <elementGuidId>444cadf8-4198-48e8-a3b7-6d492b34fdad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'fs-6']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='offerModal']/div/form/div[2]/div/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.card.bg-light.border-0.rounded-4.shadow-sm.px-4.py-2.mb-4 > div.d-flex.align-items-center > div.card-body > div.fs-6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fs-6</value>
      <webElementGuid>40c41de6-7059-4b60-b3de-724c193c1869</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='offerModal']/div/form/div[2]/div/div/div/div[2]</value>
      <webElementGuid>336fc280-11ae-4234-89c3-ba4390e81082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kucing jalanan 2'])[2]/following::div[1]</value>
      <webElementGuid>41bfdafc-09ea-4cd9-91ac-40e5f14011bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masukkan Harga Tawarmu'])[1]/following::div[5]</value>
      <webElementGuid>dfd01e21-9371-4e63-bbbc-d14511d67dc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harga Tawar'])[1]/preceding::div[1]</value>
      <webElementGuid>9ac7e945-eb5c-4154-b0c3-991506133978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/div/div[2]</value>
      <webElementGuid>fcd59983-295e-4ba4-9287-cb292948f74f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Rp 123' or . = 'Rp 123')]</value>
      <webElementGuid>2140459d-611d-4d26-bfd8-068fd594e3a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
