<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iconBackArrow</name>
   <tag></tag>
   <elementGuidId>c97e2f3f-f28b-4277-a6e8-dd72b7395c3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.bi.bi-arrow-left.fs-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'bi bi-arrow-left fs-5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bi bi-arrow-left fs-5</value>
      <webElementGuid>de3b5fa0-9820-4f35-a06c-1857390cce32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>422c31cc-3abe-417d-bfd0-7b89ecfd1ad6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
